### PR TITLE
Add sudo option

### PR DESCRIPTION
**Pull request by mschmidt18**
add option to execute command using sudo for the following methods:

hostapd.disable
hostapd.enable
ifconfig.down
ifconfig.up
iw.scan
iwlist.scan
wpa_supplicant.disable
wpa_supplicant.enable
wpa_supplicant.manual

### CODE REVIEW

**Comment by Clement-TS** [comment]
I'm against the use of sudo inside the code, tour program has to be run as root but you don't know in which context it will be used (ubuntu, mac, archlinux, lfs...).

**Review by fatihtashan — APPROVED** [review]

**Review by rzr — COMMENTED** [review]
LGTM

**Comment by shaynem** [comment]
I think it would be best to submit a PR for the readme to simply explain how to configure sudo for the specified commands for the user executing

Something as simple as 

**not recommended** 

```
/etc/sudoers.d/010_username-nopasswd
username ALL=(ALL) NOPASSWD: ALL
```

More defined list for each bin used.

```username ALL=NOPASSWD: /usr/sbin/iwlist```

**Comment by rzr** [comment]
please rebase

**Comment by mschmidt18** [comment]
> please rebase

done

**Pull request merged**
