### PR TITLE
Add wpa_cli, wpa_supplicant, scan for hidden networks, parse negative noise

### PR DESCRIPTION
**Pull request by mnkhouri**
This is a big PR, because during my development, I merged in @carlos-alarcon 's PR https://github.com/bakerface/wireless-tools/pull/5 into my dev branch. Quoting from his PR:

> I added some new 'fatures':
>iwlist:
>    scan:
>    Will be able to show hidden networks.
>    Will be able to run in 'active' mode to look for an specific hidden SSID
>wpa_supplicant:
>    disable can kill any wpasupplicant for a specific interface
>    manual: launch wpasupplicat (unconfigured) so it can receive commands from wpa_cli (to be setup)
>wpa_cli: Connect to wpasupplicant and set/update configuration

The feature that I added is:

iwlist: parse negative noise

### CODE REVIEW

**Comment by TheMSB** [comment]
This seems super useful, I was about to start implementing wpa_cli myself until I saw this. Why hasn't this been merged?

**Comment by bakerface** [comment]
Sorry, this fell off my radar. I will revisit it today and tomorrow.

**Comment by TheMSB** [comment]
> Sorry, this fell off my radar. I will revisit it today and tomorrow.

Thanks for the fast reply, I appreciate the effort.

**Comment by bakerface** [comment]
I just pushed a new release `0.16.0` with these changes.

**Pull request merged**
